"""A MODEL of `hold_arm.py`'s file channel. It is not `hold_arm.py`.

Say that first because everything downstream is measured against this file. If
the model is wrong, four phases of green tests prove a fiction.

WHAT IT REPRODUCES
    The three files the daemon exposes, and the exact lines it writes into them:

      arm_cmd.txt     consumed then TRUNCATED, one protocol line per write
      arm_hold.log    appended, `HH:MM:SS CMD <line> -> <reply>`
      arm_status.txt  rewritten on a poll, and only `if sta:`

    Every reply is generated by handing the line to a real `arm_sim.ArmSim`, so
    the wire format is the firmware's and not mine. Nothing here writes a canned
    reply string; `test_fake_daemon_conformance.py` asserts that directly.

WHY NOT JUST RUN THE REAL `hold_arm.py`
    It would need a monkeypatched `serial` module AND control of wall-clock
    time -- its loop sleeps 0.15 s and polls every 5 s, so a STALE test would
    take fifteen real seconds. `arm-sim/README.md` §7 describes exactly that
    monkeypatch recipe and records that it was DELIBERATELY NOT COMMITTED,
    "not something to leave lying around in a repo that drives motors". This
    honours that: no `serial` import anywhere in this file, no threads, no
    `time.sleep`, and the clock is a number a test moves.

WHAT IT DOES NOT MODEL -- read this before believing a green test
  - **It does not poll on its own.** The real daemon polls every 5 s whatever
    the host does. Here `poll()` fires only when a test calls it. That is a
    DELIBERATE divergence and it is what makes a STALE status file reachable
    offline: a stopped loop is exactly a daemon that has stopped polling, and
    modelling the automatic poll would make the failure untestable.
  - **`send()` costs no virtual time.** The real one sleeps `wait` (0.30 s,
    0.35 s on the health poll) and then blocks up to 1.2 s draining the reply,
    during which the interpolator runs and the `PNG` heartbeat is NOT written.
    Here feed-and-read is instantaneous. Safe direction: the model never
    manufactures a watchdog trip the real daemon would have avoided. Tests that
    care about travel call `advance()` explicitly.
  - **The startup sleeps ARE modelled, as time and nothing else.** `main()`
    sleeps 2.2 s for the port and 1.2 s after each `ENA`, so a real restart
    cannot take less than about eight seconds. That matters: it is what stops
    two daemon runs sharing an `HH:MM:SS`, which is the residual blind spot in
    `ArmLink.restarted()`. No joint travel happens across them -- `ENA <j>
    <adopt>` PRE-LOADS the pulse before attaching (arm-sim README §3,
    "adopt-before-drive"), so the joint is already there with zero elapsed time.
  - **No serial port, no baud, no transmit time, no DTR timing, no Optiboot
    window.** `start()` models the board reset that opening the port causes,
    and nothing else about opening it.
  - **No arm.** Same warning as `arm-sim/README.md` §4, and it is the important
    one: this is a model of a program that talks to a model of a firmware. It
    knows what was commanded. Nothing here observes a shaft.

THE HEARTBEAT IS MODELLED ON PURPOSE
    `advance()` writes the fire-and-forget `PNG` every 500 ms of virtual time,
    because `hold_arm.py` does (line 147) and because the alternative models a
    daemon that does not feed its own watchdog -- which is the specific bug that
    already dropped this arm once (`hold_arm.py`'s docstring, `arm-serial-control`
    §2a). Without it, advancing past 4000 ms would trip the simulated watchdog,
    latch the board, and hand Phase 2 a `LATCHED` line that the real daemon
    would never have produced. `test_fake_daemon_conformance.py` asserts the
    board does not latch across a long quiet advance, so a later edit to
    `advance()` cannot silently reintroduce that fiction.
"""

from __future__ import annotations

import os
import time

from arm_sim import ArmSim

#: Copied from `hold_arm.py`, not imported from it -- importing would drag
#: pyserial into every module that touches the fake daemon. The conformance
#: test pins all four of these to the real daemon's values, in the shape of the
#: CSV field-count validator that caught `pass=yes`.
WDG_MS = 4000
HOLD = {
    1: (0, 91, 1, 15),      # shoulder    TWO MG996R, mirror_mode=inverted
    3: (0, 66, 33, 20),     # elbow       MG996R, measured
    4: (0, 180, 90, 20),    # wrist pitch MG90S, ends UNCONFIRMED -> take the middle
    5: (31, 178, 104, 20),  # wrist roll  MG90S
    6: (10, 70, 40, 12),    # gripper     proven today
}
MIRROR = "MIR INV 0"

#: The daemon beats every `> 0.5` s of its monotonic clock. Modelled as a flat
#: 500 ms slice; the real one lands nearer 0.6 s because it is evaluated once
#: per 0.15 s loop iteration. Nothing in the bot can observe the difference.
HEARTBEAT_MS = 500

#: A fixed epoch so log timestamps and status-file mtimes are reproducible.
#: 2026-08-06 12:00:00 UTC. Any absolute value would do; the tests only ever
#: use differences and the `HH:MM:SS` shape.
EPOCH = 1_754_481_600.0


class FakeDaemon:
    """`hold_arm.py`'s file channel, with the clock as an argument.

    Not thread-safe and not threaded: every state change happens inside a call
    a test made. `pump()`, `poll()`, `advance()` and `restart()` are the whole
    surface.
    """

    def __init__(self, link_dir: str, now: float = EPOCH, port_name: str = "SIM"):
        self.dir = link_dir
        self.cmd = os.path.join(link_dir, "arm_cmd.txt")
        self.log_path = os.path.join(link_dir, "arm_hold.log")
        self.status = os.path.join(link_dir, "arm_status.txt")
        self.now = now
        #: The real daemon says "opening COM5". This says "opening SIM", and the
        #: difference is deliberate: no test in this repo should carry a string
        #: that reads like an instruction to open the real port. Nothing in the
        #: bot parses this line -- `ArmLink` only ever looks for `CMD <line> -> `.
        self.port_name = port_name
        self.sim = ArmSim()

    # -- the daemon's own two primitives ------------------------------------

    def log(self, msg: str) -> None:
        """`hold_arm.log()`, minus the `print`. The format is load-bearing.

        `ArmLink` finds a reply by searching for `CMD <line> -> ` and then cuts
        at the next line carrying this `HH:MM:SS ` prefix. Note that a
        MULTI-LINE reply gets ONE timestamp -- only the first line -- which is
        why the cut is not a newline cut. See `arm_link.py`.
        """
        line = f"{time.strftime('%H:%M:%S', time.localtime(self.now))} {msg}"
        with open(self.log_path, "a", encoding="utf-8") as fh:
            fh.write(line + "\n")

    def send(self, line: str) -> str:
        """`hold_arm.send()`: flush stale input, write the line, drain the reply.

        `discard_out()` is `reset_input_buffer()` -- it is what throws away the
        replies to the fire-and-forget `PNG` heartbeats that piled up since the
        last command.
        """
        self.sim.discard_out()
        self.sim.feed((line + "\n").encode("ascii"))
        return self.sim.read_out().decode("ascii", "replace").strip()

    # -- startup ------------------------------------------------------------

    def start(self) -> None:
        """`main()` down to "HOLDING", including the log truncation on line 96.

        NOTE WHAT IS NOT TOUCHED: `arm_status.txt`. The daemon never truncates
        or deletes it, so after a restart a stale status file from the previous
        run survives, with its old mtime, until the first poll. A shrunken log
        beside an unchanged status file is exactly the shape plan finding 3
        describes.
        """
        open(self.log_path, "w").close()  # hold_arm.py:96
        self.log(f"opening {self.port_name} (this DTR-resets the board)")
        self.sim.reset()  # opening the port asserts DTR and resets the board
        self._settle(2200)  # hold_arm.py:99 -- the Optiboot window
        self.sim.discard_out()  # hold_arm.py:100 -- the banner is flushed

        self.log("VER  -> " + self.send("VER"))
        self.log("CLR  -> " + self.send("CLR"))
        self.log("WDG  -> " + self.send(f"WDG {WDG_MS}"))

        # Limits and speed BEFORE enabling -- LIM is refused on a live joint.
        for jid, (lo, hi, _adopt, dps) in HOLD.items():
            self.log(f"LIM {jid} -> " + self.send(f"LIM {jid} {lo} {hi} 1"))
            self.log(f"SPD {jid} -> " + self.send(f"SPD {jid} {dps}"))
            if jid == 1:
                # Immediately after joint 1's LIM, and while it is still
                # disabled -- an INV offset is validated against joint 1's range.
                self.log(f"{MIRROR} -> " + self.send(MIRROR))

        # Proximal to distal, so each joint settles before the next one loads it.
        for jid in sorted(HOLD):
            adopt = HOLD[jid][2]
            self.log(f"ENA {jid} {adopt} -> " + self.send(f"ENA {jid} {adopt}"))
            self._settle(1200)  # hold_arm.py:121

        self.log("STA  -> " + self.send("STA").replace("\n", " | "))
        self.log("HOLDING. joints " + ",".join(str(j) for j in sorted(HOLD)) +
                 " energised. j0 excluded -- its servo is dead.")
        self.log(f"command channel: write a protocol line into {self.cmd}")

    def restart(self) -> None:
        """What the operator sees as "I restarted the daemon".

        It is `start()`, and that is the finding: the log is TRUNCATED TO ZERO
        BYTES and every joint is re-driven to its adopt angle by `ENA`. A bot
        holding a byte offset across this seeks past EOF and tails an empty
        string forever, so every command hangs to timeout -- while the arm has
        just snapped to five adopt angles with nobody having asked it to.
        `ArmLink.restarted()` is what catches it.
        """
        self.start()

    # -- the loop, one piece at a time --------------------------------------

    def enable_all(self) -> None:
        """`hold_arm.enable_all()`. The `  re-ENA` prefix (two spaces) is what
        `motion_verify.py` and Phase 2 both scan the log window for."""
        for j in sorted(HOLD):
            lo, hi, adopt, dps = HOLD[j]
            self.send(f"LIM {j} {lo} {hi} 1")
            self.send(f"SPD {j} {dps}")
            self.log(f"  re-ENA {j} {adopt} -> " + self.send(f"ENA {j} {adopt}"))

    def poll(self) -> None:
        """The 5 s health check. Fires only when a test calls it -- see the
        module docstring on why that divergence is deliberate."""
        sta = self.send("STA")
        if not sta:
            return  # hold_arm.py:161 -- a live process whose STA came back
            # empty leaves a STALE status file behind and looks perfectly healthy
        with open(self.status, "w", encoding="utf-8") as fh:
            fh.write(sta)
        os.utime(self.status, (self.now, self.now))

        if "ES=1" in sta or "WD=1" in sta:
            self.log("LATCHED (ES/WD) -- the arm has dropped. Clearing and re-enabling.")
            self.log("CLR -> " + self.send("CLR"))
            self.enable_all()
        elif " EN=1" not in sta:
            self.log("every joint reports EN=0 with no latch -- re-enabling.")
            self.enable_all()

    def pump(self) -> None:
        """The command channel: consume `arm_cmd.txt`, clear it, log each reply.

        `ArmLink.send()` wires this to its `on_poll` hook, which is the whole
        reason that hook exists -- nothing else can append the reply while a
        test is blocked inside `send()`.
        """
        try:
            if os.path.exists(self.cmd) and os.path.getsize(self.cmd) > 0:
                with open(self.cmd, "r", encoding="utf-8") as fh:
                    lines = [ln.strip() for ln in fh if ln.strip()]
                open(self.cmd, "w").close()
                for ln in lines:
                    self.log(f"CMD {ln} -> " + self.send(ln))
        except OSError:
            pass

    def _settle(self, ms: int) -> None:
        """A `time.sleep()` inside the startup handshake: time, no heartbeat.

        The real daemon writes no `PNG` here -- the loop has not started. It
        does not need to: every complete protocol line feeds the watchdog, and
        the handshake sends one every 0.3-1.2 s. The 2.2 s port wait is the one
        long gap and no joint is enabled across it, so the watchdog is not even
        armed (it needs `wdgMs != 0` AND an enabled joint).
        """
        self.now += ms / 1000.0
        self.sim.advance(ms)

    def advance(self, ms: float) -> None:
        """Move virtual time forward, beating the watchdog on the way.

        Both clocks move together: the wall clock the log timestamps and the
        status-file mtime come from, and the firmware's own clock. Decoupling
        them would model a daemon whose board never ages, which is not a daemon.
        """
        if ms < 0:
            raise ValueError("time does not run backwards")
        remaining = float(ms)
        while remaining > 0:
            slice_ms = min(HEARTBEAT_MS, remaining)
            self.now += slice_ms / 1000.0
            self.sim.advance(int(slice_ms))
            # FIRE AND FORGET. Writing the byte is what feeds the watchdog; the
            # reply is never read and is discarded by the next send().
            self.sim.feed(b"PNG\n")
            remaining -= slice_ms

    def wedge(self, ms: float) -> None:
        """The loop STOPS while the board goes on running. `advance()`'s twin.

        `advance()` models a healthy daemon and so keeps writing `PNG`. But a
        `STALE` verdict means the loop is not running -- and a loop that has
        stopped polling has also stopped feeding the 4000 ms watchdog. Modelling
        that with `advance()` would keep the board fed for the whole window and
        build a state the real failure never has.

        What this constructs is the 2026-08-06 evening failure, which is the
        reason the freshness verdict exists at all: the watchdog trips,
        `estopAll` DETACHES every joint, and `arm_status.txt` -- written at the
        last poll and never rewritten since -- sits on disk still reporting
        `EN=1` on all five. A stale status file reads exactly like a healthy
        held arm, and Telegram is the surface where that does the most damage
        because the reader cannot glance at the bench.

        It does not distinguish crashed from wedged from laptop-asleep. Neither
        can the bot. All three read `STALE`, and all three refuse.
        """
        if ms < 0:
            raise ValueError("time does not run backwards")
        self.now += ms / 1000.0
        self.sim.advance(int(ms))

    # -- test conveniences, not modelled behaviour --------------------------

    def write_cmd(self, line: str) -> None:
        """What `ArmLink.send()` does to the command file. Here so a test can
        exercise `pump()` without going through the link client."""
        with open(self.cmd, "w", encoding="utf-8") as fh:
            fh.write(line + "\n")

    def read_log(self) -> str:
        with open(self.log_path, "r", encoding="utf-8", errors="replace") as fh:
            return fh.read()
